# File is inherited by all apps handled by config-server.
# If custom microservice properties file exists, is overriden.

parentMessage: Hello Spring Actuator! Finally!

management:
  endpoints:
    web:
      exposure:
        include: '*'

# Opcjonalne jeśli zostawimy domyślny adres eureki (:8761)
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

# Opcjonalne jeśli zostawimy domyślny adres serwera konfiguracyjnego (:8888)
spring:
  cloud:
    config:
      uri: http://config-server:8888