spring:
  application:
    name: gateway-service

server:
  port: 8080


spring:
  cloud:
    config:
      uri: http://localhost:8888

zuul:
  routes:
    notifications:
      path: /notifications/**
      url: http://localhost:10001/