spring:
  application:
    name: gateway-service

server:
  port: 8080

ribbon:
  eureka:
    enabled: true

zuul:
  routes:
    notifications:
      path: /notifications/**
      url: http://localhost:10001/