spring:
  application:
    name: gateway-service

server:
  port: 80

ribbon:
  eureka:
    enabled: true

zuul:
  routes:
    notifications:
      path: /notifications/**
      serviceId: notification-service
    config-server:
      path: /config-server/**
      serviceId: config-server
    eureka-server:
      path: /eureka/**
      serviceId: eureka-server
    dashboard:
      path: /dashboard/**
      serviceId: dashboard